### Incluir uma ativo financeiro do tipo ação
POST http://localhost:8080/acoes
Content-Type: application/json
Authorization: "Bearer token"

## body
{
  "nome": "Embraer",
  "sigla": "EMBR3",
  "moeda": "BRL",
  "descricao": "Projeto. Desenvolvimento. Fabricação. Comercialização de Aeronaves E Sistemas E Fornecimento de Suporte E Serviços de Pós-venda.",
  "razaoSocial": "Embraer S.A.",
  "website": "http://www.embraer.com.br/"
}

### Deletar um ativo financeiro do tipo ação
DELETE /http://localhost:8080/acoes/20ae5dc1-8f98-4c61-b8ce-7aadfcd808f9
